import React from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle } from 'lucide-react';
import usePageMeta from '../../hooks/usePageMeta';

const Disclaimer = () => {
  usePageMeta(
    'Disclaimer - TurboTags: Important Service Information',
    'TurboTags Disclaimer: Understand the limitations of AI-generated content. No guarantees on virality or success. Use generated tags and hashtags responsibly.'
  );
  return (
    <main className="container mx-auto max-w-4xl p-6 py-10">
      <div className="bg-white p-8 rounded-xl shadow-lg">
        <div className="text-center border-b pb-4 mb-8">
            <AlertTriangle className="h-12 w-12 text-yellow-500 mx-auto mb-4" />
            <h1 className="text-4xl font-bold mb-2" style={{color: '#475569'}}>Disclaimer</h1>
            <p className="text-gray-500">Last updated: July 11, 2025</p>
        </div>
        
        <div className="space-y-8 text-gray-700 leading-relaxed">
          <section>
            <h2 className="text-2xl font-bold mb-3" style={{color: '#475569'}}>1. General Information Only</h2>
            <p>The information and tools provided by TurboTags ("we," "us," or "our") on https://turbotags.app (the "Site") are for general informational and educational purposes only. All information on the Site is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or generated content on the Site.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold mb-3" style={{color: '#475569'}}>2. No Guarantee of Results</h2>
            <p>The tags, hashtags, and other content generated by our AI are suggestions based on algorithms and available data. <strong>Their use does not guarantee any specific outcomes, such as virality, increased views, follower growth, or revenue.</strong> Your success is dependent on numerous factors outside of our control, including but not limited to your content quality, consistency, audience engagement, and unpredictable changes in platform algorithms.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold mb-3" style={{color: '#475569'}}>3. Not Professional Advice</h2>
            <p>The information available on the Site is not intended to be, and shall not be understood or construed as, professional marketing, financial, or legal advice. The information is not a substitute for advice from a qualified professional who is aware of the facts and circumstances of your individual situation. Your use of any information provided on this site is solely at your own risk.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3" style={{color: '#475569'}}>4. External Links</h2>
            <p>The Site may contain links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, or completeness by us. We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the Site.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3" style={{color: '#475569'}}>5. Limitation of Liability</h2>
            <p><strong>UNDER NO CIRCUMSTANCE SHALL WE HAVE ANY LIABILITY TO YOU FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF THE SITE OR RELIANCE ON ANY INFORMATION PROVIDED ON THE SITE. YOUR USE OF THE SITE AND YOUR RELIANCE ON ANY INFORMATION ON THE SITE IS SOLELY AT YOUR OWN RISK.</strong></p>
          </section>
        </div>
        <div className="text-center mt-12 pt-6 border-t">
            <Link to="/" className="btn-primary">I Understand, Back to Home</Link>
        </div>
      </div>
    </main>
  );
};

export default Disclaimer;
